[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "12.16.2"
  NODE_ENV = "production"

[dev]
  command = "npm run start"
  publish = "dist"

[[redirects]]
  from = "/conference"
  to = "https://jamstackconf.com/"
  status = 302

[[redirects]]
  from = "/slack"
  to = "https://join.slack.com/t/jamstack/shared_invite/zt-kp3asm76-~0QDRYOeBjnd1Hk9tMTAtA"
  status = 302

[[redirects]]
  from = "/best-practices"
  to = "/resources"
  status = 301

[[redirects]]
  from = "/diversity"
  to = "/code-of-conduct"
  status = 301

[[redirects]]
  from = "/benefits"
  to = "/why-jamstack"
  status = 301

[[redirects]]
  from = "/img/og/glossary/:term/:summary"
  to = "https://res.cloudinary.com/netlify/image/fetch/c_fit,l_text:Roboto_65_bold::term,co_rgb:FFFFFF,g_north_west,y_75,x_100,w_1000/c_fit,l_text:Roboto_38_light::summary,co_rgb:FFFFFF,g_north_west,y_200,x_160,w_885/https://jamstack.org/img/og/glossary-card-bg.png"
  status = 200

[[redirects]]
  from = "/glossary/*"
  to = "/glossary/contribute/index.html"
  status = 404


[[plugins]]
  package = "./plugins/keep-dot-cache-folder"
